version: '2.1'
services:
  janus-gateway:
    image: 'janus-moe'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "80:80"
      - "443:443"
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
      - "42000-50000:42000-50000"
    volumes:
      - "./config:/usr/local/etc/janus"
      - "./sites-enabled:/etc/nginx/sites-enabled/"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    restart: 'no'
